# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jonas/workerThreadPool/pajeng

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jonas/workerThreadPool/pajeng

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jonas/workerThreadPool/pajeng/CMakeFiles /home/jonas/workerThreadPool/pajeng/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jonas/workerThreadPool/pajeng/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named paje_library

# Build rule for target.
paje_library: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 paje_library
.PHONY : paje_library

# fast build rule for target.
paje_library/fast:
	$(MAKE) -f src/libpaje/CMakeFiles/paje_library.dir/build.make src/libpaje/CMakeFiles/paje_library.dir/build
.PHONY : paje_library/fast

#=============================================================================
# Target rules for targets named pjflex

# Build rule for target.
pjflex: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pjflex
.PHONY : pjflex

# fast build rule for target.
pjflex/fast:
	$(MAKE) -f src/fb/CMakeFiles/pjflex.dir/build.make src/fb/CMakeFiles/pjflex.dir/build
.PHONY : pjflex/fast

#=============================================================================
# Target rules for targets named pjflex_library

# Build rule for target.
pjflex_library: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pjflex_library
.PHONY : pjflex_library

# fast build rule for target.
pjflex_library/fast:
	$(MAKE) -f src/fb/CMakeFiles/pjflex_library.dir/build.make src/fb/CMakeFiles/pjflex_library.dir/build
.PHONY : pjflex_library/fast

#=============================================================================
# Target rules for targets named pj_dump

# Build rule for target.
pj_dump: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pj_dump
.PHONY : pj_dump

# fast build rule for target.
pj_dump/fast:
	$(MAKE) -f src/tools/CMakeFiles/pj_dump.dir/build.make src/tools/CMakeFiles/pj_dump.dir/build
.PHONY : pj_dump/fast

#=============================================================================
# Target rules for targets named pj_validate

# Build rule for target.
pj_validate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pj_validate
.PHONY : pj_validate

# fast build rule for target.
pj_validate/fast:
	$(MAKE) -f src/tools/CMakeFiles/pj_validate.dir/build.make src/tools/CMakeFiles/pj_validate.dir/build
.PHONY : pj_validate/fast

#=============================================================================
# Target rules for targets named paje_utils_library

# Build rule for target.
paje_utils_library: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 paje_utils_library
.PHONY : paje_utils_library

# fast build rule for target.
paje_utils_library/fast:
	$(MAKE) -f src/utils/CMakeFiles/paje_utils_library.dir/build.make src/utils/CMakeFiles/paje_utils_library.dir/build
.PHONY : paje_utils_library/fast

#=============================================================================
# Target rules for targets named man

# Build rule for target.
man: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 man
.PHONY : man

# fast build rule for target.
man/fast:
	$(MAKE) -f doc/CMakeFiles/man.dir/build.make doc/CMakeFiles/man.dir/build
.PHONY : man/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... paje_library"
	@echo "... pjflex"
	@echo "... pjflex_library"
	@echo "... pj_dump"
	@echo "... pj_validate"
	@echo "... paje_utils_library"
	@echo "... man"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

